#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "marrero373.cstcis.cti.depaul.edu";
$SERVER_PORT = 6011;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
